-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 11:20:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Stock_manager` ;

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stock_manager` DEFAULT CHARACTER SET utf8 ;
USE `Stock_manager` ;

-- -----------------------------------------------------
-- Table `Stock_manager`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Location` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `IDPiece` INT NOT NULL,
  `duree` DATE NOT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Etat_Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Etat_Location` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Etat_Location` (
  `idEtat_Location` INT NOT NULL AUTO_INCREMENT,
  `Etat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEtat_Location`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Produit` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `ID` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  `fkEtat_location` INT NOT NULL,
  PRIMARY KEY (`idProduit`),
  INDEX `fk_Produit_Etat_Location_idx` (`fkEtat_location` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_Produit_Etat_Location`
    FOREIGN KEY (`fkEtat_location`)
    REFERENCES `Stock_manager`.`Etat_Location` (`idEtat_Location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`LocPro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`LocPro` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`LocPro` (
  `fkProduit` INT NOT NULL,
  `fkLocation` INT NOT NULL,
  PRIMARY KEY (`fkProduit`, `fkLocation`),
  INDEX `fk_Produit_has_Location_Location1_idx` (`fkLocation` ASC),
  INDEX `fk_Produit_has_Location_Produit1_idx` (`fkProduit` ASC),
  CONSTRAINT `fk_Produit_has_Location_Produit1`
    FOREIGN KEY (`fkProduit`)
    REFERENCES `Stock_manager`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Location_Location1`
    FOREIGN KEY (`fkLocation`)
    REFERENCES `Stock_manager`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`login` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`login` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = INNODB;


INSERT INTO Etat_Location (Etat) VALUES 
('En stock'),
('Louer');

INSERT INTO Login (login,mdp) VALUES
('vendeur','$2y$10$uYNhdyOrmRfEb2mCvlx5b.MLuBb/.NXMLyEoWZxKYpzkCC///JZ.O');-- mot de passe Pa$$w0rd


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
