-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 14:01:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Stock_manager` ;

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stock_manager` DEFAULT CHARACTER SET utf8 ;
USE `Stock_manager` ;

-- -----------------------------------------------------
-- Table `Stock_manager`.`Etat_Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Etat_Location` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Etat_Location` (
  `idEtat_Location` INT NOT NULL AUTO_INCREMENT,
  `Etat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEtat_Location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Produit` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `ID` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  `fkEtat_location` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `fkEtat_location`),
  INDEX `fk_Produit_Etat_Location_idx` (`fkEtat_location` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_Produit_Etat_Location`
    FOREIGN KEY (`fkEtat_location`)
    REFERENCES `Stock_manager`.`Etat_Location` (`idEtat_Location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Location` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `IDPiece` INT NOT NULL,
  `duree` DATE NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `Produit_idProduit`),
  INDEX `fk_Location_Produit1_idx` (`Produit_idProduit` ASC),
  CONSTRAINT `fk_Location_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `Stock_manager`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Etat_Location (Etat) VALUES 
('En stock'),
('Louer');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
