-- MySQL Script generated by MySQL Workbench
-- Thu Mar  8 14:36:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Stock_manager` ;

-- -----------------------------------------------------
-- Schema Stock_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stock_manager` DEFAULT CHARACTER SET utf8 ;
USE `Stock_manager` ;

-- -----------------------------------------------------
-- Table `Stock_manager`.`Loueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Loueur` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Loueur` (
  `idLoueur` INT NOT NULL AUTO_INCREMENT,
  `nomLoueur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLoueur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Produit` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idProduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stock_manager`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock_manager`.`Location` ;

CREATE TABLE IF NOT EXISTS `Stock_manager`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `Duree` INT NOT NULL,
  `fkLoueur` INT NOT NULL,
  `fkProduit` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `fkLoueur`, `fkProduit`),
  INDEX `fk_Loueur_has_Produit_Produit1_idx` (`fkProduit` ASC),
  INDEX `fk_Loueur_has_Produit_Loueur_idx` (`fkLoueur` ASC),
  CONSTRAINT `fk_Loueur_has_Produit_Loueur`
    FOREIGN KEY (`fkLoueur`)
    REFERENCES `Stock_manager`.`Loueur` (`idLoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loueur_has_Produit_Produit1`
    FOREIGN KEY (`fkProduit`)
    REFERENCES `Stock_manager`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'vendeur'@'localhost' IDENTIFIED BY 'Pa$$w0rd';
GRANT select, insert, update, delete, execute ON stock_manager . * TO 'vendeur'@'localhost';
FLUSH PRIVILEGES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
